### ISSUE TITLE
Oh my god! Its steal my facebook!

### ISSUE THREAD

**Issue by Miraichi** [DanyaTangens/Elements-Mod-Terraria#3]
эээ свышь майн отдай ээ че ножик появился все можно? 
![image](https://user-images.githubusercontent.com/20600632/58378943-db814100-7fb5-11e9-9931-f2672401fa04.png)

**Comment by DanyaTangens** [comment]
da ti zaebal, otbam ya tebe kluchik na minecraft !!!!

**Comment by Miraichi** [comment]
![Screenshot](https://media-elerium.cursecdn.com/avatars/36/185/635935292977718780.png)

**Comment by Miraichi** [comment]
Гони давай

**Comment by Miraichi** [comment]
Гони давай
